"""Sector result-reading registry & router (SECTOR_RESULT_PLAYBOOK.md §4).

Generalises the binary ``is_bfsi`` switch into a per-sector lookup: every result
is routed by its ``SectorClass`` to a ``SectorSpec`` (operating line + verdict
rule + built flag). BFSI is the one BUILT sector; the rest declare their schema
and return a low-confidence neutral until their rule lands (the P1 out-of-scope
guard — this is what stops the engine emitting a confident verdict for a sector
it cannot yet read, e.g. the ONGC false LONG).

Public API:

    from nse_data.fundamentals.sectors import classify_result, spec_for, sector_class_for

    verdict = classify_result("ONGC", growth, fields)   # routed, guarded
    spec    = spec_for("HDFCBANK")                       # the SectorSpec
    klass   = sector_class_for("INFY")                   # SectorClass.IT

Adding a sector = add its module + one line in ``REGISTRY`` + one real-PDF
regression. Nothing else changes.
"""
from __future__ import annotations

from ..earnings_quality import QualityVerdict
from . import (
    auto,
    bfsi,
    capital_goods,
    energy,
    fmcg,
    generic,
    it_services,
    metals,
    pharma,
    realty,
)
from .base import (
    INDEX_TO_CLASS,
    SYMBOL_TO_CLASS,
    SectorClass,
    SectorSpec,
    apply_narrative,
    enrich_signal,
    out_of_scope_verdict,
    unbuilt_spec,
)

# sector_class → its spec. The single place a new sector is registered.
REGISTRY: dict[SectorClass, SectorSpec] = {
    SectorClass.BFSI: bfsi.SPEC,
    SectorClass.ENERGY: energy.SPEC,
    SectorClass.IT: it_services.SPEC,
    SectorClass.FMCG: fmcg.SPEC,
    SectorClass.AUTO: auto.SPEC,
    SectorClass.PHARMA: pharma.SPEC,
    SectorClass.METALS: metals.SPEC,
    SectorClass.CAPGOODS: capital_goods.SPEC,
    SectorClass.REALTY: realty.SPEC,
    SectorClass.GENERIC: generic.SPEC,
}

# A spec for symbols we can't place — out-of-scope, never confident.
_UNKNOWN_SPEC = unbuilt_spec(SectorClass.UNKNOWN, kpis=())


def sector_class_for(symbol: str) -> SectorClass:
    """Resolve a symbol to its SectorClass via the sectoral-index mapping.

    Resolution order:
      1. ``base.SYMBOL_TO_CLASS`` overrides (capital goods has no
         constituent-backed index; ABB/SIEMENS/BHEL are misfiled under energy).
      2. Sectoral-index membership (config/sector_mapping.yaml).
      3. The long tail: NSE's own quote-metadata taxonomy
         (``metadata_class_by_symbol``, generated by build_sector_mapping.py
         via ``base.class_for_metadata`` — banks→BFSI, non-bank financials
         deliberately unrouted, recognised industries→their sector, the rest
         →GENERIC).
    Anything still unresolved is ``UNKNOWN`` (out-of-scope neutral)."""
    from ...market.sector_map import (  # lazy: avoid import cycle
        index_class_for, metadata_class_for, sector_for,
    )

    symbol = symbol.upper()
    override = SYMBOL_TO_CLASS.get(symbol)
    if override is not None:
        return override
    index = sector_for(symbol)
    if index:
        klass = INDEX_TO_CLASS.get(index.upper())
        if klass is not None:
            return klass
    meta = metadata_class_for(symbol)
    if meta:
        try:
            return SectorClass(meta)
        except ValueError:
            pass   # stale config value from a newer/older code vintage
    # Full-universe fallback: NSE index-CSV sector → class (config/sector_class_
    # map.yaml). Consulted AFTER index + quote-metadata so the bank routing they
    # own wins; Financial Services is absent from this map (the lender guard).
    idx_cls = index_class_for(symbol)
    if idx_cls:
        try:
            return SectorClass(idx_cls)
        except ValueError:
            pass
    return SectorClass.UNKNOWN


def spec_for(symbol: str) -> SectorSpec:
    """The SectorSpec a symbol's result should be read with."""
    return REGISTRY.get(sector_class_for(symbol), _UNKNOWN_SPEC)


def classify_result(
    symbol: str,
    growth: dict | None,
    fields: dict | None = None,
    narrative: dict | None = None,
    surprise: dict | None = None,
) -> QualityVerdict:
    """Route a result to its sector rule and apply the P1 built guard.

    For a BUILT sector this is the sector's own verdict. For any sector whose
    rule is not yet validated (``built=False``), the verdict is downgraded to an
    explicit out-of-scope neutral regardless of what the draft rule computes, so
    the engine stays trustworthy only where it has been proven (playbook §5).

    ``narrative`` is the filing's press-release signal dict
    (``NarrativeFields.as_dict()``, P7 — guidance / volumes / FDA / order book);
    when present it is folded into the P&L verdict via ``apply_narrative``,
    using the sector's own operating line for the guidance gate.

    ``surprise`` is the optional fundamental-surprise dict (``events.matcher`` —
    carries ``surprise_basis`` 'consensus'|'trend'); a real consensus surprise
    lifts the v2 confidence to HIGH. Every returned verdict carries the v2 axes
    (confidence / metrics / kpi_signals) via ``enrich_signal``."""
    spec = spec_for(symbol)
    if not spec.built:
        return enrich_signal(
            out_of_scope_verdict(spec.sector_class), spec.sector_class,
            growth, narrative, surprise)
    verdict = spec.classify(growth, fields)
    if narrative:
        verdict = apply_narrative(
            verdict, growth, narrative, spec.sector_class, spec.operating_line,
        )
    return enrich_signal(verdict, spec.sector_class, growth, narrative, surprise)


__all__ = [
    "SectorClass",
    "SectorSpec",
    "REGISTRY",
    "sector_class_for",
    "spec_for",
    "classify_result",
]
