"""
Stock -> sector lookup (Week 8, task 8.3/8.4).

Loads config/sector_mapping.yaml (generated by scripts/build_sector_mapping.py
from raw_index_members) and answers "what sector is this symbol in?". Cached on
first load; the mapping changes only a few times a year.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import yaml

DEFAULT_PATH = "config/sector_mapping.yaml"

# Sectoral indices whose constituents file a BANK/NBFC-style P&L (Interest
# Earned / Interest Expended / Provisions / Operating Profit), so the financial
# extractor must read the BFSI lines, not a generic revenue/PAT P&L. PSU & private
# bank indices are listed even when sparsely populated in sector_mapping.yaml.
BFSI_SECTORS = frozenset({
    "NIFTY BANK",
    "NIFTY PSU BANK",
    "NIFTY PRIVATE BANK",
    "NIFTY FINANCIAL SERVICES",
})


@lru_cache(maxsize=4)
def load_sector_map(path: str = DEFAULT_PATH) -> dict[str, str]:
    """{symbol: sectoral-index}. Empty dict if the file is missing/empty."""
    p = Path(path)
    if not p.exists():
        return {}
    data = yaml.safe_load(p.read_text()) or {}
    return dict(data.get("sector_by_symbol", {}))


def sector_for(symbol: str, path: str = DEFAULT_PATH) -> str | None:
    return load_sector_map(path).get(symbol)


@lru_cache(maxsize=4)
def load_metadata_class_map(path: str = DEFAULT_PATH) -> dict[str, str]:
    """{symbol: sector-class value} — the long-tail routing derived from NSE's
    own quote-metadata taxonomy (generated alongside sector_by_symbol by
    scripts/build_sector_mapping.py). Empty dict if absent (older config)."""
    p = Path(path)
    if not p.exists():
        return {}
    data = yaml.safe_load(p.read_text()) or {}
    return dict(data.get("metadata_class_by_symbol", {}))


def metadata_class_for(symbol: str, path: str = DEFAULT_PATH) -> str | None:
    return load_metadata_class_map(path).get(symbol)


INDEX_CLASS_PATH = "config/sector_class_map.yaml"


@lru_cache(maxsize=2)
def load_index_class_map(path: str = INDEX_CLASS_PATH) -> dict[str, str]:
    """{symbol: sector-class value} from NSE index-constituent CSVs (full-universe
    coverage; generated by scripts/build_sector_class_map.py). A flat mapping,
    Financial Services omitted by design (lender guard). Empty dict if absent."""
    p = Path(path)
    if not p.exists():
        return {}
    data = yaml.safe_load(p.read_text()) or {}
    # tolerate either a flat map or one nested under a key
    if isinstance(data, dict) and "sector_class_by_symbol" in data:
        data = data["sector_class_by_symbol"]
    return {str(k).upper(): str(v) for k, v in data.items()} if isinstance(data, dict) else {}


def index_class_for(symbol: str, path: str = INDEX_CLASS_PATH) -> str | None:
    return load_index_class_map(path).get(symbol.upper())


CURATED_SECTORS_PATH = "config/curated_sectors.yaml"


@lru_cache(maxsize=2)
def load_curated_sector_map(path: str = CURATED_SECTORS_PATH) -> dict[str, str]:
    """{symbol: sector-class value} hand-maintained sector routing.

    NSE's /api/quote-equity (the per-symbol industry source) went behind Akamai
    (~2026-05-20), so symbols outside the sectoral-index constituents can't be
    auto-classified. This map — generated/maintained by
    scripts/build_curated_sectors.py — routes financials AND the tradeable
    non-financial tail deterministically (lender guard applied at build time).
    Empty dict if absent."""
    p = Path(path)
    if not p.exists():
        return {}
    data = yaml.safe_load(p.read_text()) or {}
    if isinstance(data, dict) and "curated_sector_by_symbol" in data:
        data = data["curated_sector_by_symbol"]
    return {str(k).upper(): str(v) for k, v in data.items()} if isinstance(data, dict) else {}


def curated_sector_for(symbol: str, path: str = CURATED_SECTORS_PATH) -> str | None:
    return load_curated_sector_map(path).get(symbol.upper())


def is_bfsi(symbol: str, path: str = DEFAULT_PATH) -> bool:
    """True if the symbol is a bank that files a BFSI-shaped P&L.

    Used by the financial extractor to request the BFSI line items (NII, PPOP,
    provisions, treasury, GNPA/NNPA) that a generic P&L read would discard.
    Index membership first; banks outside the four indices are caught via the
    quote-metadata routing (class_for_metadata maps only actual banks to bfsi).
    """
    if symbol and symbol.upper() in _BFSI_SYMBOL_OVERRIDES:
        return True
    if sector_for(symbol, path) in BFSI_SECTORS:
        return True
    return metadata_class_for(symbol, path) == "bfsi"


# BANKS the index + metadata routing misses (PSU + small-finance banks are sparsely populated
# in the sector feeds). Curated from extractor eval misclassifications. NBFCs are deliberately
# EXCLUDED: they file a normal Ind-AS P&L (Revenue from operations), not the bank Schedule-III
# format, so the BFSI schema HURTS them (CGCL 11/13 → 7/13) — they belong on the generic path.
_BFSI_SYMBOL_OVERRIDES = frozenset({
    "CENTRALBK", "IDBI", "BANKINDIA", "BANKBARODA", "PNB", "CANBK", "UNIONBANK", "INDIANB",
    "UCOBANK", "MAHABANK", "PSB", "IOB", "J&KBANK", "KARURVYSYA", "SOUTHBANK", "DCBBANK",
    "CSBBANK", "RBLBANK", "BANDHANBNK", "EQUITASBNK", "UJJIVANSFB", "SURYODAY", "FINOPB",
})
