"""
Stock -> sector lookup (Week 8, task 8.3/8.4).

Loads config/sector_mapping.yaml (generated by scripts/build_sector_mapping.py
from raw_index_members) and answers "what sector is this symbol in?". Cached on
first load; the mapping changes only a few times a year.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import yaml

DEFAULT_PATH = "config/sector_mapping.yaml"


@lru_cache(maxsize=4)
def load_sector_map(path: str = DEFAULT_PATH) -> dict[str, str]:
    """{symbol: sectoral-index}. Empty dict if the file is missing/empty."""
    p = Path(path)
    if not p.exists():
        return {}
    data = yaml.safe_load(p.read_text()) or {}
    return dict(data.get("sector_by_symbol", {}))


def sector_for(symbol: str, path: str = DEFAULT_PATH) -> str | None:
    return load_sector_map(path).get(symbol)
