"""Generate config/curated_sectors.yaml — the hand-maintained sector routing for
symbols NSE's Akamai-walled /api/quote-equity can no longer classify.

Three layers, applied in order:
  1. HAND — explicit, identity-verified overrides (banks, NBFCs, fee financials,
     and the tradeable top-500 non-financials placed in their real sector).
  2. DEFER — insurers / holdings / pure-investment / fintech: kept UNKNOWN by
     design (premium/VNB not extracted; holdcos have no operating P&L).
  3. GENERIC default — every remaining UNKNOWN that is NOT lender-shaped
     (no interest_earned_cr / net_interest_income_cr in its filings) is a
     non-financial → the shared operating-quality read. Lender-shaped names not
     explicitly placed in HAND stay UNKNOWN (the lender guard: never give a
     lender the finance-cost-add-back generic read).

Re-run after curating more names or refreshing extracted_financials:
    PYTHONPATH=src .venv/bin/python scripts/build_curated_sectors.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

OUT = "config/curated_sectors.yaml"

# 1. HAND — identity-verified. Values are SectorClass string values.
HAND: dict[str, str] = {}

def _add(klass: str, syms: str) -> None:
    for s in syms.split():
        HAND[s] = klass

# Banks (incl. SFBs) — read with the bank rule.
_add("bfsi", "CENTRALBK CSBBANK CUB DCBBANK EQUITASBNK ESAFSFB IDBI IOB J&KBANK "
             "JSFB KARURVYSYA KTKBANK MAHABANK SOUTHBANK TMB UCOBANK UJJIVANSFB UTKARSHBNK")
# Non-bank lenders (NBFC / HFC / MFI / fin-institution).
_add("nbfc", "AADHARHFC AAVAS ABCAPITAL CANFINHOME CGCL CREDITACC FEDFINA FIVESTAR "
             "FUSION HDBFS HOMEFIRST HUDCO IIFL INDIASHLTR LTF M&MFIN MUFIN NORTHARC "
             "PAISALO PIRAMALFIN POONAWALLA SATIN SBFC SGFIN SPANDANA SUNDARMFIN TATACAP "
             "TFCILTD APTUS AYE BAJAJHFL CAPTRUST CIFL EDELWEISS FINKURVE IFCI JMFINANCIL "
             "MANCREDIT RELIGARE")
# Fee financials (AMC / broking / wealth / exchange).
_add("capmarkets", "5PAISA ABSLAMC ANANDRATHI ARIHANTCAP CHOICEIN DBSTOCKBRO EMKAY GROWW "
                    "ICICIAMC IIFLCAPS MASTERTR PRUDENT SHAREINDIA SMCGLOBAL UTIAMC INDOTHAI")
# Tradeable top-500 non-financials placed in their real built sector.
_add("pharma", "INDOCO MOREPENLAB ORCHPHARMA SOLARA UNICHEMLAB VENUSREM SENORES VIMTALABS LAXMIDENTL")
_add("metals", "JTLIND POCL")
_add("auto", "SANDHAR SEDEMAC")
_add("capgoods", "WENDT NIBE UNIMECH ROTO EXICOM CENTUM KERNEX MARSONS JNKINDIA PREMEXPLN WALCHANNAG")
_add("energy", "HINDOILEXP CLEANMAX")
_add("it", "MOSCHIP E2E GENESYS UNIECOM")
_add("fmcg", "GRMOVER")
# Explicit GENERIC (confident real-economy, no built sector-specific rule).
_add("generic", "ASIANTILES CAMLINFINE GOLDIAM HINDWAREAP RAYMOND GOCOLORS TBZ MOTISONS "
                "JINDWORLD YASHO MANALIPETC SHADOWFAX SHREEJISPG DREDGECORP AEROFLEX FCL")

# 2. DEFER — keep UNKNOWN by design.
DEFER = set(
    "HDFCLIFE ICICIGI ICICIPRULI LICI SBILIFE MFSL GICRE NIACL STARHEALTH GODIGIT MEDIASSIST "
    "BAJAJFINSV BAJAJHLDNG CHOLAHLDNG MAHSCOOTER TATAINVEST JIOFIN AIIL "
    "PAYTM PINELABS MOBIKWIK POLICYBZR PROTEAN KISSHT PNBGILTS".split()
)


def main() -> int:
    import sqlite3
    import yaml
    from nse_data.fundamentals.sectors import sector_class_for

    conn = sqlite3.connect("data/nse.db")
    # Current UNKNOWN universe (after index/metadata/HAND-less routing).
    extracted = [s for (s,) in conn.execute("SELECT DISTINCT symbol FROM extracted_financials")]

    # lender-shaped = a banking/NBFC XBRL income field is present → never GENERIC.
    lender = {s for (s,) in conn.execute(
        "SELECT DISTINCT symbol FROM extracted_financials "
        "WHERE interest_earned_cr IS NOT NULL OR net_interest_income_cr IS NOT NULL")}

    mapping = dict(HAND)
    generic_added = 0
    for s in extracted:
        if s in mapping or s in DEFER:
            continue
        # only place those CURRENTLY unrouted (don't override index/metadata wins)
        if sector_class_for(s).value != "unknown":
            continue
        if s in lender:
            continue                      # lender guard → stay UNKNOWN
        mapping[s] = "generic"
        generic_added += 1

    from collections import Counter
    dist = Counter(mapping.values())
    header = (
        "# Curated sector routing — symbol -> SectorClass value.\n"
        "# GENERATED by scripts/build_curated_sectors.py (re-run to refresh).\n"
        "# WHY: NSE /api/quote-equity (the per-symbol industry source) went behind\n"
        "# Akamai Bot Manager ~2026-05-20 and returns Access Denied to non-browser\n"
        "# clients on every host. This map routes deterministically without it.\n"
        "# Consulted by sectors.sector_class_for right after SYMBOL_TO_CLASS.\n"
        f"# Distribution: {dict(sorted(dist.items()))}\n"
    )
    with open(OUT, "w") as f:
        f.write(header)
        yaml.safe_dump({"curated_sector_by_symbol": dict(sorted(mapping.items()))},
                       f, default_flow_style=False, sort_keys=False)
    print(f"wrote {OUT}: {len(mapping)} symbols "
          f"({len(HAND)} hand-curated, {generic_added} generic-default), "
          f"{len(DEFER)} deferred, {len(lender)} lender-shaped guarded")
    print(f"distribution: {dict(sorted(dist.items()))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
