"""
Generate config/sector_mapping.yaml from raw_index_members (Week 8, task 8.3).

Maps each stock to its NSE sectoral index using the authoritative index
constituent lists. Only the sectoral indices the radar ranks are considered; the
broad indices (NIFTY 50/100/500) are ignored. A stock that appears in more than
one sectoral index is assigned the one where it carries the most weight (lowest
`weightage_rank`).

    python scripts/build_sector_mapping.py            # writes config/sector_mapping.yaml
    python scripts/build_sector_mapping.py --dry-run  # print summary only

Re-run after the index membership feed refreshes (constituents change a few
times a year). The mapping is committed so the dispatcher doesn't depend on the
DB being current at send time.
"""

from __future__ import annotations

import argparse

import yaml

from nse_data.market.sector_radar_job import SECTOR_INDICES
from nse_data.storage.db import open_db

OUTPUT = "config/sector_mapping.yaml"


def build_mapping(db_path: str) -> dict[str, str]:
    """symbol -> sectoral index, best-weight wins on overlap."""
    conn = open_db(db_path)
    try:
        rows = conn.execute(
            f"SELECT index_name, symbol, COALESCE(weightage_rank, 9999) "
            f"FROM raw_index_members "
            f"WHERE index_name IN ({','.join('?' * len(SECTOR_INDICES))})",
            SECTOR_INDICES,
        ).fetchall()
    finally:
        conn.close()

    best: dict[str, tuple[int, str]] = {}   # symbol -> (rank, sector)
    for sector, symbol, rank in rows:
        cur = best.get(symbol)
        if cur is None or rank < cur[0]:
            best[symbol] = (rank, sector)
    return {sym: sector for sym, (_, sector) in best.items()}


def build_metadata_classes(db_path: str) -> dict[str, str]:
    """symbol -> sector-class value, from NSE's own quote-metadata taxonomy.

    The long-tail routing for the per-sector result engine: symbols outside
    the sectoral indices get a class via ``sectors.base.class_for_metadata``
    (banks → bfsi; non-bank financials deliberately unrouted — the lender
    guard; recognised industries → their sector; other non-financials →
    generic). Re-run when the quote-metadata universe grows."""
    from nse_data.fundamentals.sectors.base import class_for_metadata

    conn = open_db(db_path)
    try:
        rows = conn.execute(
            "SELECT symbol, sector, industry FROM raw_quote_metadata"
        ).fetchall()
    except Exception:  # noqa: BLE001 — table absent on a bare DB
        rows = []
    finally:
        conn.close()

    out: dict[str, str] = {}
    for symbol, sector, industry in rows:
        klass = class_for_metadata(sector, industry)
        if klass is not None:
            out[symbol] = klass.value
    return out


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Build config/sector_mapping.yaml (task 8.3)")
    p.add_argument("--db", default="data/nse.db")
    p.add_argument("--out", default=OUTPUT)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args(argv)

    mapping = build_mapping(args.db)
    meta_classes = build_metadata_classes(args.db)

    # Per-sector counts for a quick sanity read.
    by_sector: dict[str, int] = {}
    for sector in mapping.values():
        by_sector[sector] = by_sector.get(sector, 0) + 1
    covered = sorted(by_sector)
    missing = [s for s in SECTOR_INDICES if s not in by_sector]

    print(f"mapped {len(mapping)} symbols across {len(covered)} sectors")
    for s in covered:
        print(f"  {s:18s} {by_sector[s]}")
    if missing:
        print(f"no constituent data (unmapped sectors): {', '.join(missing)}")

    by_class: dict[str, int] = {}
    for klass in meta_classes.values():
        by_class[klass] = by_class.get(klass, 0) + 1
    print(f"metadata classes for {len(meta_classes)} symbols "
          f"({', '.join(f'{k}:{v}' for k, v in sorted(by_class.items()))})")

    if args.dry_run:
        return 0

    header = (
        "# Stock -> NSE sectoral index. Generated by scripts/build_sector_mapping.py\n"
        "# Source: raw_index_members (index constituents). Re-run when membership changes.\n"
        "# Sectors without constituent data are absent here (stocks in them get no\n"
        "# sector contribution): " + (", ".join(missing) if missing else "none") + "\n"
        "# metadata_class_by_symbol: long-tail sector-class routing from NSE's own\n"
        "# quote-metadata taxonomy (raw_quote_metadata) via sectors.base.class_for_metadata.\n"
        "# Non-bank financials are deliberately absent (the lender guard).\n"
    )
    with open(args.out, "w") as f:
        f.write(header)
        yaml.safe_dump({"sector_by_symbol": dict(sorted(mapping.items())),
                        "metadata_class_by_symbol": dict(sorted(meta_classes.items()))},
                       f, default_flow_style=False, sort_keys=False)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
