"""Generate config/sector_class_map.yaml — symbol → engine SectorClass for the
whole universe, from NSE's index-constituent CSVs (the SECTOR_UNIVERSE source).

The engine's ``sector_class_for`` otherwise resolves only NSE *sectoral-index*
members + the sparse quote-metadata (~206 names), so most of the universe falls
to UNKNOWN/generic and the per-sector rules never fire. This map lights up the
full coverage: NIFTY Total Market's ``Industry`` (NSE macro sector) → SectorClass.

Deliberately OMITS "Financial Services": that macro bucket mixes banks (→ BFSI)
with NBFCs/AMCs/brokers/insurers (the lender guard — generic EBITDA is wrong for
a lender). Banks keep routing via NIFTY BANK index membership; the rest stay
out-of-scope until a lender-specific rule exists. So this map is a FALLBACK,
consulted after the index + metadata layers (which own the bank routing).

    .venv/bin/python -u scripts/build_sector_class_map.py
"""
from __future__ import annotations

import csv
import io
from pathlib import Path

import httpx
import yaml

ROOT = Path(__file__).resolve().parents[1]
_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
_INDEX_CSVS = ["ind_niftytotalmarket_list.csv", "ind_nifty500list.csv",
               "ind_niftymicrocap250_list.csv"]

# NSE index "Industry" (macro sector) → engine SectorClass value. Financial
# Services intentionally absent (lender guard). Power/Utilities → energy (the
# §2.2 power block reads an operating-EBITDA line); cement (Construction
# Materials) → metals; Construction (EPC/infra) → capgoods (shares the order-book
# + working-capital-balloon shape).
NSE_SECTOR_TO_CLASS = {
    "Information Technology": "it",
    "Oil Gas & Consumable Fuels": "energy",
    "Power": "energy",
    "Utilities": "energy",
    "Healthcare": "pharma",
    "Fast Moving Consumer Goods": "fmcg",
    "Automobile and Auto Components": "auto",
    "Capital Goods": "capgoods",
    "Construction": "capgoods",
    "Metals & Mining": "metals",
    "Construction Materials": "metals",
    "Realty": "realty",
    "Chemicals": "generic",
    "Consumer Services": "generic",
    "Consumer Durables": "generic",
    "Services": "generic",
    "Textiles": "generic",
    "Telecommunication": "generic",
    "Media Entertainment & Publication": "generic",
    "Forest Materials": "generic",
    "Diversified": "generic",
}


def main() -> int:
    out: dict[str, str] = {}
    skipped_fin = 0
    print("fetching NSE index CSVs…", flush=True)
    for f in _INDEX_CSVS:
        try:
            r = httpx.get(f"https://nsearchives.nseindia.com/content/indices/{f}",
                          headers={"User-Agent": _UA, "Referer": "https://www.nseindia.com/"},
                          timeout=30, follow_redirects=True)
            if r.status_code != 200:
                print(f"  {f}: HTTP {r.status_code}", flush=True)
                continue
            n0 = len(out)
            for row in csv.DictReader(io.StringIO(r.text)):
                sym = (row.get("Symbol") or "").strip().upper()
                ind = (row.get("Industry") or "").strip()
                if not sym or sym in out:
                    continue
                if ind == "Financial Services":
                    skipped_fin += 1
                    continue
                cls = NSE_SECTOR_TO_CLASS.get(ind)
                if cls:
                    out[sym] = cls
            print(f"  {f}: +{len(out)-n0} (total {len(out)})", flush=True)
        except Exception as e:  # noqa: BLE001
            print(f"  {f}: ERR {e}", flush=True)

    dst = ROOT / "config" / "sector_class_map.yaml"
    header = ("# symbol -> engine SectorClass, from NSE index-constituent CSVs\n"
              "# (NIFTY Total Market Industry column). Generated by\n"
              "# scripts/build_sector_class_map.py. A FALLBACK in sectors.sector_class_for,\n"
              "# consulted after index + quote-metadata (which own bank routing).\n"
              "# Financial Services is omitted by design (lender guard).\n")
    dst.write_text(header + yaml.safe_dump(dict(sorted(out.items())), sort_keys=False))
    from collections import Counter
    dist = Counter(out.values())
    print(f"\nwrote {dst.name}: {len(out)} symbols "
          f"({skipped_fin} Financial Services omitted)")
    for k, v in dist.most_common():
        print(f"  {k:10} {v}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
