"""
Generate config/sector_mapping.yaml from raw_index_members (Week 8, task 8.3).

Maps each stock to its NSE sectoral index using the authoritative index
constituent lists. Only the sectoral indices the radar ranks are considered; the
broad indices (NIFTY 50/100/500) are ignored. A stock that appears in more than
one sectoral index is assigned the one where it carries the most weight (lowest
`weightage_rank`).

    python scripts/build_sector_mapping.py            # writes config/sector_mapping.yaml
    python scripts/build_sector_mapping.py --dry-run  # print summary only

Re-run after the index membership feed refreshes (constituents change a few
times a year). The mapping is committed so the dispatcher doesn't depend on the
DB being current at send time.
"""

from __future__ import annotations

import argparse

import yaml

from nse_data.market.sector_radar_job import SECTOR_INDICES
from nse_data.storage.db import open_db

OUTPUT = "config/sector_mapping.yaml"


def build_mapping(db_path: str) -> dict[str, str]:
    """symbol -> sectoral index, best-weight wins on overlap."""
    conn = open_db(db_path)
    try:
        rows = conn.execute(
            f"SELECT index_name, symbol, COALESCE(weightage_rank, 9999) "
            f"FROM raw_index_members "
            f"WHERE index_name IN ({','.join('?' * len(SECTOR_INDICES))})",
            SECTOR_INDICES,
        ).fetchall()
    finally:
        conn.close()

    best: dict[str, tuple[int, str]] = {}   # symbol -> (rank, sector)
    for sector, symbol, rank in rows:
        cur = best.get(symbol)
        if cur is None or rank < cur[0]:
            best[symbol] = (rank, sector)
    return {sym: sector for sym, (_, sector) in best.items()}


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Build config/sector_mapping.yaml (task 8.3)")
    p.add_argument("--db", default="data/nse.db")
    p.add_argument("--out", default=OUTPUT)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args(argv)

    mapping = build_mapping(args.db)

    # Per-sector counts for a quick sanity read.
    by_sector: dict[str, int] = {}
    for sector in mapping.values():
        by_sector[sector] = by_sector.get(sector, 0) + 1
    covered = sorted(by_sector)
    missing = [s for s in SECTOR_INDICES if s not in by_sector]

    print(f"mapped {len(mapping)} symbols across {len(covered)} sectors")
    for s in covered:
        print(f"  {s:18s} {by_sector[s]}")
    if missing:
        print(f"no constituent data (unmapped sectors): {', '.join(missing)}")

    if args.dry_run:
        return 0

    header = (
        "# Stock -> NSE sectoral index. Generated by scripts/build_sector_mapping.py\n"
        "# Source: raw_index_members (index constituents). Re-run when membership changes.\n"
        "# Sectors without constituent data are absent here (stocks in them get no\n"
        "# sector contribution): " + (", ".join(missing) if missing else "none") + "\n"
    )
    with open(args.out, "w") as f:
        f.write(header)
        yaml.safe_dump({"sector_by_symbol": dict(sorted(mapping.items()))},
                       f, default_flow_style=False, sort_keys=False)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
